# Generated by Django 2.2.5 on 2019-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190924_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
